### ISSUE TITLE
get owner field in Info()

### ISSUE THREAD

**Issue by develper1** [webfoersterei/domain-bestellsystem-api-client#6]
@Hecke29 I have 1 last question please .. it is possible to get owner field in Info by domain name ..?

**Comment by develper1** [comment]
i want to get this field.
![53](https://user-images.githubusercontent.com/76731493/128712885-f0fad438-6551-4691-b1c2-8c44d909ae40.PNG)

**Comment by Hecke29** [comment]
Answered in #5 
Please bear in mind I am not the API-developer nor a support for that.

This client is a implementation against the external API. You need to take a look into the documentation to find out where to find what kind of data.

I will not answer any more questions on how to fetch certain data from the API since thats not part of this project

**Comment by develper1** [comment]
@Hecke29 ok sorry for disturb you .. thanks for helping me ..
